import { ORDEM_PARANORMAL } from "./data/ordem";
import { ChoiceOption, SystemPreset } from "./types";

const ORDEM_CLASSES: ChoiceOption[] = [
  {
    nome: "Combatente",
    grupo: "Base",
    vidaBase: 20,
    vidaPorNivel: 4,
    peBase: 2,
    pePorNivel: 1,
    sanidadeBase: 16,
    sanidadePorNivel: 3,
    defesaBonus: 1,
    proficiencias: ["Fortitude", "Luta"],
    caminhos: [
      { nome: "Aniquilador", desc: "Especialista em armas pesadas e impacto bruto.", proficiencias: ["Pontaria"] },
      { nome: "Guerreiro", desc: "Linha de frente agressiva e adaptavel.", proficiencias: ["Luta"] },
      { nome: "Operacoes Especiais", desc: "Pressao tatica e mobilidade ofensiva.", proficiencias: ["Reflexos", "Tatica"] },
      { nome: "Tropa de Choque", desc: "Absorve dano e protege a linha aliada.", proficiencias: ["Fortitude"] },
      { nome: "Personalizada", custom: true, desc: "Defina manualmente uma trilha de combatente." },
    ],
  },
  {
    nome: "Especialista",
    grupo: "Base",
    vidaBase: 16,
    vidaPorNivel: 3,
    peBase: 3,
    pePorNivel: 2,
    sanidadeBase: 18,
    sanidadePorNivel: 4,
    proficiencias: ["Crime", "Investigacao"],
    caminhos: [
      { nome: "Atirador de Elite", desc: "Precisao e controle de campo.", proficiencias: ["Pontaria", "Percepcao"] },
      { nome: "Infiltrador", desc: "Furtividade, invasao e dano oportunista.", proficiencias: ["Crime", "Furtividade"] },
      { nome: "Medico de Campo", desc: "Suporte rapido e estabilizacao em combate.", proficiencias: ["Medicina"] },
      { nome: "Negociador", desc: "Controle social e leitura de cena.", proficiencias: ["Diplomacia", "Intuicao"] },
      { nome: "Tecnico", desc: "Ferramentas, explosivos e improviso.", proficiencias: ["Tecnologia", "Profissao"] },
      { nome: "Personalizada", custom: true, desc: "Defina manualmente uma trilha de especialista." },
    ],
  },
  {
    nome: "Ocultista",
    grupo: "Base",
    vidaBase: 12,
    vidaPorNivel: 2,
    peBase: 5,
    pePorNivel: 3,
    sanidadeBase: 20,
    sanidadePorNivel: 4,
    defesaBonus: 0,
    proficiencias: ["Ocultismo", "Vontade"],
    caminhos: [
      { nome: "Conduite", desc: "Expande alcance e fluxo ritualistico.", proficiencias: ["Ocultismo"] },
      { nome: "Graduado", desc: "Aprende mais rituais e amplia repertorio.", proficiencias: ["Ocultismo", "Atualidades"] },
      { nome: "Intuitivo", desc: "Sobrevive melhor ao Outro Lado.", proficiencias: ["Vontade", "Percepcao"] },
      { nome: "Lamina Paranormal", desc: "Mistura ritual e combate direto.", proficiencias: ["Luta", "Ocultismo"] },
      { nome: "Personalizada", custom: true, desc: "Defina manualmente uma trilha de ocultista." },
    ],
  },
  {
    nome: "Personalizada",
    custom: true,
    desc: "Defina manualmente uma classe ou trilha.",
  },
];

const ORDEM_RACES: ChoiceOption[] = [
  {
    nome: "Marcado",
    desc: "Humano tocado pelo Outro Lado.",
    deslocamento: "9m",
  },
  {
    nome: "Sobrevivente",
    desc: "Versao flexivel para campanhas autorais.",
    atributos: { vigor: 1, presenca: 1 },
    deslocamento: "9m",
  },
  {
    nome: "Personalizada",
    custom: true,
    desc: "Defina manualmente uma linhagem ou condicao especial.",
  },
];

const ORDEM_MELHORIAS = [
  "Calibre grosso",
  "Cruel",
  "Certeira",
  "Tatica",
  "Reforcada",
  "Silenciada",
];

const ORDEM_MALDICOES = [
  "Sangrenta",
  "Energetica",
  "Sombria",
  "Ritualistica",
  "Repulsora",
  "Lancinante",
];

const DND5E: SystemPreset = {
  nome: "D&D 5e",
  racas: [
    {
      nome: "Humano",
      desc: "Versatil e adaptavel.",
      atributos: { forca: 1, agilidade: 1, vigor: 1, intelecto: 1, presenca: 1 },
      deslocamento: "9m",
    },
    {
      nome: "Anao",
      desc: "Resistente e obstinado.",
      atributos: { vigor: 2 },
      proficiencias: ["Fortitude", "Historia"],
      deslocamento: "7,5m",
    },
    {
      nome: "Elfo",
      desc: "Agil, atento e ligado a magia.",
      atributos: { agilidade: 2, intelecto: 1 },
      proficiencias: ["Percepcao"],
      deslocamento: "9m",
    },
    {
      nome: "Halfling",
      desc: "Pequeno, sortudo e furtivo.",
      atributos: { agilidade: 2, presenca: 1 },
      proficiencias: ["Furtividade"],
      deslocamento: "7,5m",
    },
    {
      nome: "Tiefling",
      desc: "Marcado pelo infernal e pela presenca.",
      atributos: { presenca: 2, intelecto: 1 },
      proficiencias: ["Intimidacao"],
      deslocamento: "9m",
    },
    {
      nome: "Personalizada",
      custom: true,
      desc: "Defina manualmente a raca ou linhagem.",
    },
  ],
  origens: [
    { nome: "Acolito", desc: "Ligacao com templos e tradicao.", proficiencias: ["Religiao", "Intuicao"] },
    { nome: "Criminoso", desc: "Furtividade e contatos.", proficiencias: ["Crime", "Furtividade"] },
    { nome: "Erudito", desc: "Conhecimento academico.", proficiencias: ["Historia", "Atualidades"] },
    { nome: "Heroi do Povo", desc: "Figura querida pelo povo.", proficiencias: ["Atletismo", "Sobrevivencia"] },
    { nome: "Soldado", desc: "Disciplina e experiencia de combate.", proficiencias: ["Intimidacao", "Tatica"] },
    { nome: "Personalizada", custom: true, desc: "Defina um antecedente proprio." },
  ],
  classes: [
    {
      nome: "Barbaro",
      grupo: "Marcial",
      vidaBase: 18,
      vidaPorNivel: 8,
      peBase: 2,
      pePorNivel: 1,
      sanidadeBase: 10,
      sanidadePorNivel: 1,
      defesaBonus: 1,
      proficiencias: ["Atletismo", "Fortitude"],
      caminhos: [
        { nome: "Berserker", desc: "Furia pura e agressiva." },
        { nome: "Totemico", desc: "Liga-se a espiritos animais." },
        { nome: "Personalizada", custom: true, desc: "Defina um caminho barbaro proprio." },
      ],
    },
    {
      nome: "Guerreiro",
      grupo: "Marcial",
      vidaBase: 16,
      vidaPorNivel: 7,
      peBase: 3,
      pePorNivel: 1,
      sanidadeBase: 10,
      sanidadePorNivel: 1,
      defesaBonus: 1,
      proficiencias: ["Luta", "Pontaria"],
      caminhos: [
        { nome: "Campeao", desc: "Tecnica marcial direta e consistente." },
        { nome: "Mestre de Batalha", desc: "Manobras e controle tatico." },
        { nome: "Personalizada", custom: true, desc: "Defina um arquétipo marcial proprio." },
      ],
    },
    {
      nome: "Ladino",
      grupo: "Especialista",
      vidaBase: 14,
      vidaPorNivel: 6,
      peBase: 4,
      pePorNivel: 1,
      sanidadeBase: 10,
      sanidadePorNivel: 1,
      proficiencias: ["Crime", "Furtividade"],
      caminhos: [
        { nome: "Assassino", desc: "Eliminacao precisa e letal." },
        { nome: "Trapaceiro Arcano", desc: "Ilusao, truques e magia furtiva." },
        { nome: "Personalizada", custom: true, desc: "Defina um arquétipo de ladino proprio." },
      ],
    },
    {
      nome: "Mago",
      grupo: "Arcano",
      vidaBase: 10,
      vidaPorNivel: 5,
      peBase: 6,
      pePorNivel: 2,
      sanidadeBase: 10,
      sanidadePorNivel: 1,
      proficiencias: ["Ocultismo", "Atualidades"],
      caminhos: [
        { nome: "Evocacao", desc: "Dominio ofensivo dos elementos." },
        { nome: "Adivinhacao", desc: "Leitura de futuro e controle do acaso." },
        { nome: "Personalizada", custom: true, desc: "Defina uma escola arcana propria." },
      ],
    },
    {
      nome: "Clerigo",
      grupo: "Divino",
      vidaBase: 12,
      vidaPorNivel: 6,
      peBase: 5,
      pePorNivel: 2,
      sanidadeBase: 12,
      sanidadePorNivel: 1,
      proficiencias: ["Religiao", "Intuicao"],
      caminhos: [
        { nome: "Dominio da Vida", desc: "Cura, resiliencia e amparo." },
        { nome: "Dominio da Guerra", desc: "Pressao divina em combate." },
        { nome: "Personalizada", custom: true, desc: "Defina um dominio proprio." },
      ],
    },
    { nome: "Personalizada", custom: true, desc: "Defina uma classe propria." },
  ],
  categorias_hab: [
    { id: "comum", nome: "Caracteristicas de Classe" },
    { id: "racas_hab", nome: "Tracos Raciais" },
    { id: "magias", nome: "Magias" },
    { id: "armas", nome: "Equipamentos" },
  ],
  comum: [
    { nome: "Furia", dado: "2 PE", desc: "Recebe bonus ofensivos e resiste melhor ao dano.", subcat: "Barbaro", fonte: "D&D 5e" },
    { nome: "Segundo Folego", dado: "1 PE", desc: "Recupera folego e parte da vida.", subcat: "Guerreiro", fonte: "D&D 5e" },
    { nome: "Ataque Furtivo", dado: "-", desc: "Causa dano extra quando tem vantagem ou distracao.", subcat: "Ladino", fonte: "D&D 5e" },
    { nome: "Recuperacao Arcana", dado: "-", desc: "Recupera parte do recurso magico no descanso.", subcat: "Mago", fonte: "D&D 5e" },
    { nome: "Canalizar Divindade", dado: "1 PE", desc: "Canaliza poder sagrado para efeitos de dominio.", subcat: "Clerigo", fonte: "D&D 5e" },
  ],
  racas_hab: [
    { nome: "Adaptavel", dado: "-", desc: "Recebe proficiencia adicional a escolha.", subcat: "Humano", fonte: "D&D 5e" },
    { nome: "Resiliencia Ana", dado: "-", desc: "Maior resistencia fisica e cultural.", subcat: "Anao", fonte: "D&D 5e" },
    { nome: "Sentidos Agucados", dado: "-", desc: "Percepcao superior e elegancia natural.", subcat: "Elfo", fonte: "D&D 5e" },
    { nome: "Bravura", dado: "-", desc: "Resiste ao medo com facilidade.", subcat: "Halfling", fonte: "D&D 5e" },
    { nome: "Heranca Infernal", dado: "-", desc: "Magia e resistencia inatas.", subcat: "Tiefling", fonte: "D&D 5e" },
  ],
  magias: [
    { nome: "Misseis Magicos", dado: "1 PE", desc: "Projeteis que acertam com precisao.", subcat: "Arcano", fonte: "D&D 5e" },
    { nome: "Curar Ferimentos", dado: "1 PE", desc: "Recupera pontos de vida por toque.", subcat: "Divino", fonte: "D&D 5e" },
    { nome: "Escudo Arcano", dado: "1 PE", desc: "Eleva temporariamente a defesa.", subcat: "Arcano", fonte: "D&D 5e" },
  ],
  armas: [
    { id: 1, nome: "Espada Longa", tipo: "Marcial", habilidade: "forca", dano: "1d8", critico: "19-20", alcance: "Adjacente", categoria: 0, desc: "Lamina versatil para combate direto." },
    { id: 2, nome: "Arco Longo", tipo: "Marcial", habilidade: "agilidade", dano: "1d8", critico: "20", alcance: "Longo", categoria: 0, desc: "Arma de alcance preciso." },
    { id: 3, nome: "Adaga", tipo: "Simples", habilidade: "agilidade", dano: "1d4", critico: "19-20", alcance: "Curto", categoria: 0, desc: "Leve e facil de esconder." },
    { id: 4, nome: "Cajado Arcano", tipo: "Arcano", habilidade: "intelecto", dano: "1d6", critico: "20", alcance: "Adjacente", categoria: 0, desc: "Canaliza energia magica." },
  ],
  melhoriasCatalogo: ["Obra-prima", "Prateada", "Foco arcano", "Mira precisa", "Empunhadura reforcada"],
  maldicoesCatalogo: ["Amaldicoada", "Vorpal fragmentada", "Sombria", "Raio crepitante"],
  resourceLabels: {
    vida: "Vida",
    pe: "Recurso",
    sanidade: "Resolve",
  },
  progressLabel: "Nivel",
  progressMin: 1,
  progressMax: 20,
  progressStep: 1,
  proficienciaTreino: 2,
  pericias: [
    { nome: "Acrobacia", atributo: "agilidade" },
    { nome: "Atletismo", atributo: "forca" },
    { nome: "Atualidades", atributo: "intelecto" },
    { nome: "Crime", atributo: "agilidade" },
    { nome: "Fortitude", atributo: "vigor" },
    { nome: "Furtividade", atributo: "agilidade" },
    { nome: "Historia", atributo: "intelecto" },
    { nome: "Intimidacao", atributo: "presenca" },
    { nome: "Intuicao", atributo: "presenca" },
    { nome: "Investigacao", atributo: "intelecto" },
    { nome: "Luta", atributo: "forca" },
    { nome: "Medicina", atributo: "intelecto" },
    { nome: "Natureza", atributo: "intelecto" },
    { nome: "Ocultismo", atributo: "intelecto" },
    { nome: "Percepcao", atributo: "presenca" },
    { nome: "Pontaria", atributo: "agilidade" },
    { nome: "Religiao", atributo: "presenca" },
    { nome: "Sobrevivencia", atributo: "intelecto" },
    { nome: "Tatica", atributo: "intelecto" },
  ],
};

export const PRESETS: Record<string, SystemPreset> = {
  ordem_paranormal: {
    ...(ORDEM_PARANORMAL as any),
    nome: "Ordem Paranormal",
    racas: ORDEM_RACES,
    classes: ORDEM_CLASSES,
    melhoriasCatalogo: ORDEM_MELHORIAS,
    maldicoesCatalogo: ORDEM_MALDICOES,
    resourceLabels: {
      vida: "Vida",
      pe: "PE",
      sanidade: "Sanidade",
    },
    progressLabel: "NEX",
    progressMin: 5,
    progressMax: 99,
    progressStep: 5,
    proficienciaTreino: 5,
  } as SystemPreset,
  dnd5e: DND5E as SystemPreset,
  memorias_postumas: {
    nome: "Memorias Postumas",
    origens: [{ nome: "Sobrevivente", poder: "Instinto", proficiencias: ["Vontade"] }],
    classes: [
      {
        nome: "Vanguarda",
        vidaBase: 16,
        vidaPorNivel: 4,
        peBase: 3,
        pePorNivel: 1,
        sanidadeBase: 12,
        sanidadePorNivel: 2,
        caminhos: [{ nome: "Executor" }, { nome: "Guardiao" }, { nome: "Personalizada", custom: true }],
      },
      {
        nome: "Suporte",
        vidaBase: 12,
        vidaPorNivel: 3,
        peBase: 4,
        pePorNivel: 2,
        sanidadeBase: 14,
        sanidadePorNivel: 2,
        caminhos: [{ nome: "Analista" }, { nome: "Catalisador" }, { nome: "Personalizada", custom: true }],
      },
      { nome: "Personalizada", custom: true },
    ],
    racas: [{ nome: "Humano" }, { nome: "Personalizada", custom: true }],
    categorias_hab: [{ id: "comum", nome: "Habilidades Base" }],
    armas: [],
    resourceLabels: {
      vida: "Vida",
      pe: "Foco",
      sanidade: "Stress",
    },
    progressLabel: "Nivel",
    progressMin: 1,
    progressMax: 20,
    progressStep: 1,
    proficienciaTreino: 2,
  } as SystemPreset,
};
